### ISSUE TITLE
4.56 compatible?

### ISSUE THREAD

**Issue by getgray** [jpearman/rcfs#1]
Should this be compatible with version 4.56?

**Comment by jpearman** [comment]
probably, I can't say I've used or tested this recently, the code is very old.

**Comment by getgray** [comment]
Thanks.  Anything newer for carefully writing a non-volatile variable on a cortex?   We need a configuration variable, something that gets read at startup, and when we change fields, the ability to test, choose a setting and once chosen, write that to memory so the program can re-read it when it starts back up.  Basically be able to programmatically change a constant.  Writing it rarely, but the ability would make it so we didn’t have to redownload the code when that change needed to happen.

**Comment by jpearman** [comment]
I checked this code in RobotC 4.56 and it still works.
you would probably want to base your code on the lcdAutonDemo
